### ISSUE TITLE
mimic-response?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/decompress-response#11]
What problem does its use solve?

**Comment by sindresorhus** [comment]
It guarantees that the user gets back something that looks like a HTTP response stream, even though it's really a unzip stream.

**Comment by stevenvachon** [comment]
Thank you. Why is `PassThrough()` needed?

**Comment by kevva** [comment]
https://github.com/sindresorhus/decompress-response/pull/4

**Comment by stevenvachon** [comment]
> …and return a PassThrough stream instead of a piped stream

Doesn't answer "why".
