### ISSUE TITLE
Support br encoding

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/decompress-response#12]
Brotli is the arguably the best HTTP compression algorithm available. Compared to gzip, it's faster and produces smaller artifacts [ref](https://certsimple.com/blog/nginx-brotli). There are two modules I'd consider for decompressing `br` responses:

https://github.com/mayhemydg/iltorb
https://github.com/devongovett/brotli.js

The first is a native module, but from my experience runs pretty well cross-platform.

cc @kevva

**Comment by sindresorhus** [comment]
Brotli should really be in Node.js core. Can you open an issue about that?

The native package is a no go as native addons are awful for users.

**Comment by silverwind** [comment]
> The native package is a no go as native addons are awful for users.

I'd argue against that, there are good native modules, and sooner or later n-api is going to fix that issue.

**Comment by sindresorhus** [comment]
> and sooner or later n-api is going to fix that issue.

Yes, but that's not now. I've tried using native packages previously many times and it was always an annoying experience for both me and users. I had to deal with so many dumb compilation issues and other things. Because of that, my personal rule is no native addons in module dependencies.

I'd rather have WebAssembly in Node.js and use the WebAssembly version of the official Brotli library.

**Comment by kevva** [comment]
One thing that suggest that `iltorb` might be a good choice is it's issue tracker though. It has ~3k downloads/day and only one open issue. But I agree on your stance though that you'll want to avoid native dependencies as much as possible.

**Comment by silverwind** [comment]
Also to add, iltorb offers prebuild binaries for all major node versions and is regularly updated for new Node versions.

**Comment by sindresorhus** [comment]
A native dependency is just not happening. Another reason `iltorb` is a no-go is that it uses `node-pre-gyp` which depends on `request`. So `got` would indirectly depend on `request`.

**Comment by silverwind** [comment]
> got would indirectly depend on request

It's only used once during installation, but yeah, it would stay in `node_modules`, unused.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/decompress-response/pull/13#issuecomment-331626197

**Comment by silverwind** [comment]
Brotli is now included in Node.js since 11.7.0, I think this should be reopened.

**Comment by kevva** [comment]
Will reopen the PR as well with added support for Brotli if it's available.
