### ISSUE TITLE
Stream is not destroyed on error

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/decompress-response#25]
Instead, an `error` event is emitted:

https://github.com/sindresorhus/decompress-response/blob/a31bde7a6bfe23345e41531ffa1a22cedbd4eadd/index.js#L32

This causes `getStream()` to hang on Node.js 14.1.0.

**Comment by sindresorhus** [comment]
Which stream should be destroyed? I thought streams are automatically destroyed on error unless there's a handler.

**Comment by szmarczak** [comment]
> I thought streams are automatically destroyed on error unless there's a handler.

The thing is that there **is** a handler. If there's an error of any kind, Got tries to read the response. But since the stream is not destroyed, it just hangs on Node.js >= 14.0.0.

I'd just replace

https://github.com/sindresorhus/decompress-response/blob/a31bde7a6bfe23345e41531ffa1a22cedbd4eadd/index.js#L25-L35

with

```js
	const finalStream = streamPipeline(response, decompress, stream, error => {
		if (error) {
			if (error.code === 'Z_BUF_ERROR') {
				stream.end();
				return;
			}

			stream.destroy(error);
		}
	});
```

**Comment by sindresorhus** [comment]
Sounds good. You know streams better than me.

**Comment by szmarczak** [comment]
Nah, I just randomly stumbled upon a Got issue and found a culprit :P But it doesn't throw on Node.js 13 so probably something has changed under the hood.

**Comment by szmarczak** [comment]
I think it's either https://github.com/nodejs/node/pull/31182/files or https://github.com/nodejs/node/pull/32158/files or maybe both. But it's nice to see stream improvements.
