### ISSUE TITLE
content-encoding header should be removed

### ISSUE THREAD

**Issue by snytkine** [sindresorhus/decompress-response#28]
Return of this function is instance of http.IncomingMessage 
The problem is that this function does not delete content-encoding header, so the result is that you have an IncomingMessage object with content-encoding header with original value like 'gzip' but the stream is no longer compressed.

I think the the function should also delete content-encoding header before returning the result stream

**Comment by sindresorhus** [comment]
That's a good find 👍🏻

**Comment by cardosob** [comment]
I think this change introduced a different issue.

The header "content-encoding" is removed from the original `response` object but the content is only decompressed in the `finalStream` object.

So you end up with a `response` object without the header and with the content still compressed.

In a context where this `response` object goes through multiple handlers, this is a problem.

@sindresorhus @snytkine

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/decompress-response/releases/tag/v9.0.0

**Comment by cardosob** [comment]
Thanks for looking into this @sindresorhus. 

Is there any chance to release this as a fix for v7.0 ? i.e. 7.0.1 or simply 7.1.0

**Comment by sindresorhus** [comment]
While it is a bug fix, changing this in v7 (or v8) is simply too risky. Some users may depend on the current behavior.

**Comment by cardosob** [comment]
I understand. Thanks @sindresorhus ! 🙇
