### ISSUE TITLE
`invalid header check` when `Content-Encoding: deflate` and it's raw deflate.

### ISSUE THREAD

**Issue by danielgindi** [sindresorhus/decompress-response#34]
Should be using `zlib.createInflateRaw`.

**Comment by sindresorhus** [comment]
Why?

---

> Decompress either a Gzip- or Deflate-compressed stream by auto-detecting the header.
> - https://nodejs.org/api/zlib.html#class-zlibunzip

**Comment by danielgindi** [comment]
> Why?
> 
> 
> 
> ---
> 
> 
> 
> > Decompress either a Gzip- or Deflate-compressed stream by auto-detecting the header.
> 
> > - https://nodejs.org/api/zlib.html#class-zlibunzip

Because this method detects based on the binary header.
But I encountered deflate reaponses without headers, which only `inflateRaw` could parse.
If the `Content-Encoding` says `deflate`, then we do not need to auto-detect, we already know the answer.

**Comment by sindresorhus** [comment]
The problem is that you cannot always trust the content encoding either (internet reality is messy). It's generally safer to rely on the binary header. But I guess the code could fall back to `inflatRaw` if `Content-Encoding: deflate` and `unzip` fails.
