### ISSUE TITLE
this project got renamed?

### ISSUE THREAD

**Issue by pnemade** [sindresorhus/decompress-response#9]
I maintain packages in Fedora. This package I saw moved from unzip-response to decompress-response. Also, now unzip-response is redirecting to decompress-response so I have no way what happened?
Things I need to know
1) Is unzip-response now deprecated? if yes then I will remove this package from Fedora and will add new decompress-response package.
2) But I also need at same time new nodejs-got module upstream release. otherwise I will be having nodejs-got package in Fedora which needs unzip-response whereas its renamed to decompress-response now.

**Comment by sindresorhus** [comment]
Please stop packaging individual Node.js modules as Fedora packages.
